sequenceDiagram
    participant browser as Przeglądarka
    participant server as Serwer
    

    Note over browser: Użytkownik wpisuje nową notatkę i klika "Zapisz"!

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: HTML z aktualną listą notatek!
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML dokument (home page)!
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: Plik CSS!
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: Plik JavaScript!
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: JSON z listą notatek
    deactivate server

    Note over browser: Przeglądarka renderuje po raz kolejny całą listę notatek!
